#lang racket
; 1.9 Using the substitution model, illustrate the process generated by each procedure in evaluating (plus-v1 4 5) and (plus-v2 4 5). Are these processes iterative or recursive?

(define (plus-v1 a b)
  (if (= a 0) 
      b 
      (inc (plus-v1 (dec a) b))))
      
; THIS IS A RECURSIVE PROCESS because the `inc` procedure needs to wait for the return value of the other computation      
#|
(plus-v1 4 5)
(inc (plus-v1 3 5))
(inc (inc (plus-v1 2 5)))
(inc (inc (inc (plus-v1 1 5))))
(inc (inc (inc (inc (plus-v1 0 5)))))
(inc (inc (inc (inc 5))))
(inc (inc (inc 6)))
(inc (inc 7))
(inc 8)
9
|#
; Implementation 2
; THIS IS AN ITERATIVE PROCESS because there are no computations being left behind
(define (plus-v2 a b)
  (if (= a 0) 
      b 
      (plus-v2 (dec a) (inc b))))
      
(plus-v2 4 5)
(plus-v2 3 6)
(plus-v2 2 7)
(plus-v2 1 8)
(plus-v2 0 9)

